/**
 * @file SOA_Adapter_Generated.c
 * @brief SOA Adapter Configuration — Auto-Generated Signal Read/Write Functions and Service Table
 *
 * Generated by soa_adapter_generator.py
 * Date: 2026-05-18 17:45:54
 * DBC source:  D:\MySandbox\SDV_Project\IPCF_FreeRTOS_S32G399A_M7_Oring\Tools\CAN_Tools\SOA_DBC_File\CANdbc_file.dbc
 * Excel source: D:\MySandbox\SDV_Project\IPCF_FreeRTOS_S32G399A_M7_Oring\Tools\CAN_Tools\SOA_DBC_File\S2S_HPC_A_SAG.xlsx
 *
 * Signal Mapping:
 *   Notifier VehicleSpeed             → Can_Get_Rx_signal_VehicleSpeed() (RX Standard_200_Rx)
 *   Getter   ParkingSts               → Can_Get_Rx_signal_ParkingSts() (RX Standard_200_Rx)
 *   Getter   HighVoltageBatterySts    → Can_Get_Rx_signal_HighVoltageBatterySts() (RX Standard_200_Rx)
 *   Getter   IgnitionSts              → Can_Get_Rx_signal_IgnitionSts() (RX Standard_200_Rx)
 *   Setter   VehicleMode              → APP_SW_R_W_signal_VehicleMode() (APP VECTOR__INDEPENDENT_SIG_MSG)
 *   Notifier WorkVehicleModeSt        → APP_SW_R_W_signal_WorkVehicleModeSt() (APP VECTOR__INDEPENDENT_SIG_MSG)
 */

#if defined(__cplusplus)
extern "C"{
#endif

/*==================================================================================================
 *                                         INCLUDE FILES
 *==================================================================================================*/

#include "SOA_Adapter_Generated.h"
#include "CANdbc_Generated.h"   /* DBC global structs and signal access functions */

/*==================================================================================================
 *                              SIGNAL READ FUNCTIONS (Notifier + Getter)
 *
 * Each function reads the current value from the DBC global variable,
 * serializes it into big-endian byte order, and returns the byte count.
 *==================================================================================================*/

/**
 * @brief Read VehicleSpeed signal (Notifier: Atom_VCU_DriSpeedSt)
 *
 * Source: Standard_200_Rx (RX, sender=SDV_Tester)
 * Serialized as 2 bytes, big-endian.
 */
uint16 SOA_ReadVehicleSpeed(uint8 *outBuf, uint16 maxLen)
{
    if ((outBuf == NULL_PTR) || (maxLen < 2U))
    {
        return 0U;
    }
    uint16_t val = Can_Get_Rx_signal_VehicleSpeed();
    outBuf[0] = (uint8)(val >> 8U);
    outBuf[1] = (uint8)(val & 0xFFU);
    return 2U;
}

/**
 * @brief Read ParkingSts signal (Getter: Atom_VCU_ParkingSt)
 *
 * Source: Standard_200_Rx (RX, sender=SDV_Tester)
 * Serialized as 1 byte, big-endian.
 */
uint16 SOA_ReadParkingSts(uint8 *outBuf, uint16 maxLen)
{
    if ((outBuf == NULL_PTR) || (maxLen < 1U))
    {
        return 0U;
    }
    uint8_t val = Can_Get_Rx_signal_ParkingSts();
    outBuf[0] = (uint8)(val & 0xFFU);
    return 1U;
}

/**
 * @brief Read HighVoltageBatterySts signal (Getter: Atom_VCU_HighVoltageBatterySt)
 *
 * Source: Standard_200_Rx (RX, sender=SDV_Tester)
 * Serialized as 2 bytes, big-endian.
 */
uint16 SOA_ReadHighVoltageBatterySts(uint8 *outBuf, uint16 maxLen)
{
    if ((outBuf == NULL_PTR) || (maxLen < 2U))
    {
        return 0U;
    }
    uint16_t val = Can_Get_Rx_signal_HighVoltageBatterySts();
    outBuf[0] = (uint8)(val >> 8U);
    outBuf[1] = (uint8)(val & 0xFFU);
    return 2U;
}

/**
 * @brief Read IgnitionSts signal (Getter: Atom_VCU_IgnitionSt)
 *
 * Source: Standard_200_Rx (RX, sender=SDV_Tester)
 * Serialized as 1 byte, big-endian.
 */
uint16 SOA_ReadIgnitionSts(uint8 *outBuf, uint16 maxLen)
{
    if ((outBuf == NULL_PTR) || (maxLen < 1U))
    {
        return 0U;
    }
    uint8_t val = Can_Get_Rx_signal_IgnitionSts();
    outBuf[0] = (uint8)(val & 0xFFU);
    return 1U;
}

/**
 * @brief Read WorkVehicleModeSt signal (Notifier: Atom_BCM_VehicleMode)
 *
 * Source: VECTOR__INDEPENDENT_SIG_MSG (virtual/app signal)
 * Serialized as 1 byte, big-endian.
 */
uint16 SOA_ReadWorkVehicleModeSt(uint8 *outBuf, uint16 maxLen)
{
    if ((outBuf == NULL_PTR) || (maxLen < 1U))
    {
        return 0U;
    }
    uint8_t val = APP_SW_R_W_signal_WorkVehicleModeSt(NULL);
    outBuf[0] = (uint8)(val & 0xFFU);
    return 1U;
}

/*==================================================================================================
 *                              SIGNAL WRITE FUNCTIONS (Setter)
 *==================================================================================================*/

/**
 * @brief Write VehicleMode signal (Setter: Atom_BCM_VehicleMode)
 *
 * Target: VECTOR__INDEPENDENT_SIG_MSG (app signal)
 * Expects 1 byte input.
 */
uint8 SOA_WriteVehicleMode(const uint8 *inBuf, uint16 len)
{
    if ((inBuf == NULL_PTR) || (len < 1U))
    {
        return 1U;  /* Error */
    }
    uint8_t val = inBuf[0];
    APP_SW_R_W_signal_VehicleMode(&val);

    return 0U;  /* Success */
}

/*==================================================================================================
 *                              SOA SERVICE CONFIGURATION TABLE
 *==================================================================================================*/

/**
 * @brief SOA service configuration table
 *
 * Index order matches SOA_SVC_IDX_xxx defines in SOA_Adapter_Generated.h.
 */
const SOA_ServiceConfig_t g_soaServiceTable[SOA_SERVICE_TABLE_COUNT] =
{
    /* [0] Atom_VCU_DriSpeedSt — Notifier: VehicleSpeed */
    {
        .SOA_ServiceID      = SOA_SID_VCU_DRI_SPEED,       /* 0x0001U */
        .SOA_MethodID       = SOA_MID_DRI_SPEED_NOTIF,     /* 0x8001U */
        .SOA_InstanceID     = SOA_INSTANCE_ID_DEFAULT,      /* 0x0001 */
        .serviceType        = SOA_SERVICE_NOTIFIER,
        .readFunc           = SOA_ReadVehicleSpeed,
        .writeFunc          = NULL_PTR,
        .SOA_EventGroupID   = SOA_EG_DRI_SPEED_SWT_STS,       /* 0x0001U */
        .dataSize           = 2U,
        .hasLinkedNotifier  = FALSE,
        .linkedNotifierIdx  = 0U
    },

    /* [1] Atom_VCU_ParkingSt — Getter: ParkingSts */
    {
        .SOA_ServiceID      = SOA_SID_VCU_PARKING,       /* 0x0002U */
        .SOA_MethodID       = SOA_MID_PARKING_GETTER,     /* 0x5001U */
        .SOA_InstanceID     = SOA_INSTANCE_ID_DEFAULT,      /* 0x0001 */
        .serviceType        = SOA_SERVICE_GETTER,
        .readFunc           = SOA_ReadParkingSts,
        .writeFunc          = NULL_PTR,
        .SOA_EventGroupID   = 0U,
        .dataSize           = 1U,
        .hasLinkedNotifier  = FALSE,
        .linkedNotifierIdx  = 0U
    },

    /* [2] Atom_VCU_HighVoltageBatterySt — Getter: HighVoltageBatterySts */
    {
        .SOA_ServiceID      = SOA_SID_VCU_HIGH_VOLTAGE_BATTERY,       /* 0x0003U */
        .SOA_MethodID       = SOA_MID_HIGH_VOLTAGE_BATTERY_GETTER,     /* 0x5001U */
        .SOA_InstanceID     = SOA_INSTANCE_ID_DEFAULT,      /* 0x0001 */
        .serviceType        = SOA_SERVICE_GETTER,
        .readFunc           = SOA_ReadHighVoltageBatterySts,
        .writeFunc          = NULL_PTR,
        .SOA_EventGroupID   = 0U,
        .dataSize           = 2U,
        .hasLinkedNotifier  = FALSE,
        .linkedNotifierIdx  = 0U
    },

    /* [3] Atom_VCU_IgnitionSt — Getter: IgnitionSts */
    {
        .SOA_ServiceID      = SOA_SID_VCU_IGNITION,       /* 0x0004U */
        .SOA_MethodID       = SOA_MID_IGNITION_GETTER,     /* 0x5001U */
        .SOA_InstanceID     = SOA_INSTANCE_ID_DEFAULT,      /* 0x0001 */
        .serviceType        = SOA_SERVICE_GETTER,
        .readFunc           = SOA_ReadIgnitionSts,
        .writeFunc          = NULL_PTR,
        .SOA_EventGroupID   = 0U,
        .dataSize           = 1U,
        .hasLinkedNotifier  = FALSE,
        .linkedNotifierIdx  = 0U
    },

    /* [4] Atom_BCM_VehicleMode — Setter: VehicleMode */
    {
        .SOA_ServiceID      = SOA_SID_BCM_VEHICLE_MODE,       /* 0x0005U */
        .SOA_MethodID       = SOA_MID_VEHICLE_MODE_SETTER,     /* 0x5001U */
        .SOA_InstanceID     = SOA_INSTANCE_ID_DEFAULT,      /* 0x0001 */
        .serviceType        = SOA_SERVICE_SETTER,
        .readFunc           = NULL_PTR,                      /* Setter: no readFunc, uses linked Notifier */
        .writeFunc          = SOA_WriteVehicleMode,
        .SOA_EventGroupID   = 0U,
        .dataSize           = 1U,
        .hasLinkedNotifier  = TRUE,
        .linkedNotifierIdx  = SOA_SVC_IDX_VEHICLE_MODE_NOTIF  /* Index 5 */
    },

    /* [5] Atom_BCM_VehicleMode — Notifier: WorkVehicleModeSt */
    {
        .SOA_ServiceID      = SOA_SID_BCM_VEHICLE_MODE,       /* 0x0005U */
        .SOA_MethodID       = SOA_MID_VEHICLE_MODE_NOTIF,     /* 0x8001U */
        .SOA_InstanceID     = SOA_INSTANCE_ID_DEFAULT,      /* 0x0001 */
        .serviceType        = SOA_SERVICE_NOTIFIER,
        .readFunc           = SOA_ReadWorkVehicleModeSt,
        .writeFunc          = NULL_PTR,
        .SOA_EventGroupID   = SOA_EG_VEHICLE_MODE_STS,       /* 0x0001U */
        .dataSize           = 1U,
        .hasLinkedNotifier  = FALSE,
        .linkedNotifierIdx  = 0U
    },

};

/**
 * @brief Notifier index mapping
 *
 * Lists indices into g_soaServiceTable for all Notifier-type services.
 * Used for initial value sync and change detection.
 */
const uint8 g_soaNotifierIndices[SOA_NOTIFIER_COUNT] =
{
    SOA_SVC_IDX_DRI_SPEED_NOTIF,    /* [0] → g_soaServiceTable[0] */
    SOA_SVC_IDX_VEHICLE_MODE_NOTIF    /* [1] → g_soaServiceTable[5] */
};

#if defined(__cplusplus)
}
#endif
