/**
 * @file picc_api.c
 * @brief PICC Driver Public API — Implementation
 *
 * This file contains ONLY the 8 public API functions.
 * All internal logic is delegated to:
 *   - picc_mailbox.c  : App registration, mailbox store/read
 *   - picc_service.c  : Event sending, method/response protocol
 *   - picc_link.c     : Link state management
 *
 * @par Communication Protocol Directionality Summary:
 * ========================================================================
 * 1. EVENT (Fire-and-Forget / Unidirectional Notification)
 *    - Ext: M-Core -> A-Core: M-Core initiates by calling PICC_SendEvent().
 *    - Rcv: A-Core -> M-Core: Incoming notification is fetched by polling 
 *                             PICC_GetEventData(), or instantly caught by 
 *                             the registered 'eventHandler'.
 * 
 * 2. METHOD (Request-Response / Bidirectional RPC)
 *    a) M-Core is Client (M-Core initiates):
 *       - Request  [M->A]: M-Core calls PICC_MethodRequest().
 *       - Response [A->M]: M-Core calls PICC_GetResponseData() to poll A-Core's reply.
 *    
 *    b) M-Core is Server (A-Core initiates):
 *       - Request  [A->M]: Fetched via PICC_GetMethodData() or caught 
 *                          instantly via the registered 'methodHandler'.
 *       - Response [M->A]: After processing, M-Core MUST call PICC_MethodResponse() 
 *                          to return the result back to A-Core.
 * ========================================================================
 *
 * Copyright 2024 NXP
 * All Rights Reserved.
 */

#if defined(__cplusplus)
extern "C" {
#endif

#include "picc_api.h"
#include "picc_mailbox.h"
#include "picc_service.h"
#include "picc_link.h"
#include "ipcf_Ip_Cfg_Defines.h"  /* For IPCF_INSTANCE0 */

/*==================================================================================================
 *                              Public API — Initialization (1 function)
 *==================================================================================================*/

/**
 * @brief Register an application with the PICC driver and initialize its context
 *
 * This function must be called by each application module (e.g., PWSM, OTA) before using 
 * any other PICC transmission or reception APIs. It registers the module's Provider ID,
 * optional Method/Event callbacks, sets up the mailbox, and initializes the underlying
 * IPCF channel.
 *
 * @par Callback Documentation:
 * When initializing PICC_Init(), you can pass callback functions in 'config'. 
 *
 * @warning ⚠️ ISR CONTEXT EXECUTION WARNING ⚠️
 *          Both `methodHandler` and `eventHandler` run directly within the IPCF hardware 
 *          RX Interrupt Service Routine (ISR) context.
 *          Application implementations MUST adhere to the following strict rules:
 *          1. **MAX EXECUTION TIME**: Must not exceed 50 microseconds.
 *          2. **NO BLOCKING**: Absolutely NO blocking OS calls (e.g., vTaskDelay, blocking on Semaphores/Mutexes).
 *          3. **PURPOSE**: Only use for instant hardware capture or rapid non-blocking state updates.
 * @par eventHandler Signature:
 * `void My_EventHandler(uint8 providerId, uint8 eventId, const uint8 *data, uint16 len, uint8 *cbResult, uint16 *cbResultLen)`
 *  - @b providerId : [Input] The A-Core Server's Provider ID that broadcasted this event.
 *  - @b eventId    : [Input] The specific Event ID generated by A-Core.
 *  - @b data       : [Input] Raw notification payload data sent from A-Core.
 *  - @b len        : [Input] Length of the notification payload.
 *  - @b cbResult   : [Output] Buffer mapped to PICC mailbox. M-Core handler writes its instant calculation result here.
 *  - @b cbResultLen: [Output] Indicates how many bytes of 'cbResult' the M-Core handler populated.
 *
 * @par methodHandler Signature:
 * `uint8 My_MethodHandler(uint8 consumerId, uint8 methodId, const uint8 *reqData, uint16 reqLen, uint8 *rspData, uint16 *rspLen, uint8 *cbResult, uint16 *cbResultLen)`
 *  - @b consumerId : [Input] The A-Core Client's ID who initiated this Method Request.
 *  - @b methodId   : [Input] The Method ID A-Core wants to call on M-Core.
 *  - @b reqData    : [Input] Raw request payload data block sent from A-Core.
 *  - @b reqLen     : [Input] Length of the request payload data.
 *  - @b rspData    : [Output] Buffer for M-Core handler to write the Response data to be sent back to A-Core.
 *  - @b rspLen     : [Output] Length of the Response data M-Core wants to send back.
 *  - @b cbResult   : [Output] Buffer mapped to PICC mailbox. M-Core handler writes its internal parsing result here.
 *  - @b cbResultLen: [Output] Indicates how many bytes of 'cbResult' the M-Core handler populated.
 *
 * @param[in] appIndex Application index from PICC_AppIndex_e enum (e.g., PICC_APP_PWR).
 * @param[in] config   Pointer to application configuration (IDs, role, channel,
 *                     and optional Method/Event callbacks).
 *
 * @return PICC_E_OK        on success
 * @return PICC_E_PARAM     if config is NULL or appIndex is out of range
 * @return PICC_E_NOT_INIT  if PICC infrastructure (mailbox) not yet initialized
 */
sint8 PICC_Init(PICC_AppIndex_e appIndex, const PICC_AppConfig_t *config)
{
    PICC_LinkConfig_t linkCfg;
    sint8 ret;

    if (config == NULL) {
        return PICC_E_PARAM;
    }
    if ((uint8)appIndex >= (uint8)PICC_APP_MAX) {
        return PICC_E_PARAM;
    }
    if (PICC_MailboxIsReady() == FALSE) {
        return PICC_E_NOT_INIT;
    }

    /* 1. Register app in mailbox context */
    ret = PICC_MailboxRegisterApp(appIndex, config);
    if (ret != PICC_E_OK) {
        return ret;
    }

    /* 2. Register Link (per-app, does NOT clear other apps' contexts) */
    linkCfg.localId    = config->localId;
    linkCfg.remoteId   = config->remoteId;
    linkCfg.role       = config->role;
    linkCfg.channelId  = config->channelId;
    linkCfg.instanceId = IPCF_INSTANCE0;
    linkCfg.Client_linkReq_PeriodMs = config->Client_linkReq_PeriodMs;
    linkCfg.isUsed     = TRUE;
    ret = PICC_LinkRegisterApp(&linkCfg);
    if (ret != 0) {
        PICC_MailboxUnregisterApp(appIndex);
        return ret;
    }

    /* 3. Register Method handler (optional) */
    if (config->methodHandler != NULL) {
        (void)PICC_RegisterMethodHandler(config->localId, config->methodHandler);
    }

    /* 4. Register Event handler (optional) */
    if (config->eventHandler != NULL) {
        (void)PICC_RegisterEventHandler(config->remoteId, config->eventHandler);
    }

    return PICC_E_OK;
}

/*==================================================================================================
 *                              Public API — Sending M->A (3 functions)
 *==================================================================================================*/

/**
 * @brief Send an Event notification from M-Core to A-Core
 */
sint8 PICC_SendEvent(PICC_AppIndex_e appIndex, uint8 eventId,
                     const uint8 *data, uint16 len, PICC_EventType_e withAck)
{
    const PICC_AppConfig_t *cfg;
    sint8 ret;

    if (PICC_MailboxIsReady() == FALSE) {
        return PICC_E_NOT_INIT;
    }

    ret = PICC_MailboxGetAppConfig(appIndex, &cfg);
    if (ret != PICC_E_OK) {
        return PICC_E_PARAM;
    }

    if (PICC_LinkGetStateByIds(cfg->localId, cfg->remoteId) != PICC_LINK_STATE_CONNECTED) {
        return PICC_E_NOT_CONNECTED;
    }

    return PICC_ServiceEventSend(cfg->localId, eventId, cfg->remoteId,
                                 data, len, withAck, cfg->channelId);
}

/**
 * @brief Send a Method Request from M-Core to A-Core
 */
uint8 PICC_MethodRequest(PICC_AppIndex_e appIndex, uint8 methodId,
                         const uint8 *data, uint16 len,
                         PICC_MethodType_e type)
{
    const PICC_AppConfig_t *cfg;
    sint8 ret;

    if (PICC_MailboxIsReady() == FALSE) {
        return 0U;
    }

    ret = PICC_MailboxGetAppConfig(appIndex, &cfg);
    if (ret != PICC_E_OK) {
        return 0U;
    }

    if (PICC_LinkGetStateByIds(cfg->localId, cfg->remoteId) != PICC_LINK_STATE_CONNECTED) {
        return 0U;
    }

    return PICC_ServiceMethodSend(cfg->remoteId, methodId, data, len, type,
                                  IPCF_INSTANCE0, cfg->channelId);
}

/**
 * @brief Send a Method Response from M-Core to A-Core
 */
sint8 PICC_MethodResponse(PICC_AppIndex_e appIndex, uint8 methodId,
                          uint8 sessionId, uint8 returnCode,
                          const uint8 *data, uint16 len)
{
    const PICC_AppConfig_t *cfg;
    sint8 ret;

    if (PICC_MailboxIsReady() == FALSE) {
        return PICC_E_NOT_INIT;
    }

    ret = PICC_MailboxGetAppConfig(appIndex, &cfg);
    if (ret != PICC_E_OK) {
        return PICC_E_PARAM;
    }

    return PICC_ServiceResponseSend(cfg->localId, cfg->remoteId, methodId, sessionId,
                                    returnCode, data, len, IPCF_INSTANCE0, cfg->channelId);
}

/*==================================================================================================
 *                              Public API — Receiving A->M (3 functions)
 *==================================================================================================*/

/**
 * @brief Retrieve a Method Request sent by A-Core to M-Core (M-Core is Server)
 *
 * Polling API for M-Core application tasks. It queries the local mailbox to see if 
 * A-Core has sent a new Method Request for the specified methodId. If a 'methodHandler' 
 * callback was registered, this function also retrieves the secondary calculation result 
 * ('cbResult') produced instantly by that callback.
 *
 * @param[in]  appIndex    M-Core Application index (e.g., PICC_APP_OTA).
 * @param[in]  methodId    The specific Method ID M-Core is looking for.
 * @param[out] data        Buffer to store the raw payload data sent by A-Core.
 * @param[in]  maxLen      Maximum size of the 'data' buffer provided by M-Core.
 * @param[out] actualLen   Returns the actual length of the payload data received from A-Core.
 * @param[out] cbResult    Buffer to store the result produced by the M-Core callback handler (pass NULL if not needed/registered).
 * @param[out] cbResultLen Returns the length of the callback result (pass NULL if not needed/registered).
 *
 * @return PICC_E_OK      = New request from A-Core was successfully retrieved.
 *         PICC_E_NO_DATA = No new request from A-Core has arrived yet.
 *         PICC_E_PARAM   = Invalid parameters provided.
 */
sint8 PICC_GetMethodData(PICC_AppIndex_e appIndex, uint8 methodId,
                         uint8 *data, uint16 maxLen, uint16 *actualLen,
                         uint8 *outSessionId,
                         uint8 *cbResult, uint16 *cbResultLen)
{
    return PICC_MailboxGetMethodData(appIndex, methodId, data, maxLen, actualLen,
                                     outSessionId, cbResult, cbResultLen);
}

/**
 * @brief Retrieve a Method Response returned by A-Core to M-Core (M-Core is Client)
 *
 * After M-Core calls PICC_MethodRequest(), it uses this API in a periodic task to check 
 * if A-Core has replied. Once A-Core replies, M-Core reads the target returnCode and data.
 *
 * @param[in]  appIndex    M-Core Application index (e.g., PICC_APP_PWR).
 * @param[in]  methodId    The Method ID mapping to the original request sent by M-Core.
 * @param[out] returnCode  Buffer to store the return code sent back by A-Core.
 * @param[out] data        Buffer to store the response payload data generated by A-Core.
 * @param[in]  maxLen      Maximum size of the 'data' buffer provided by M-Core.
 * @param[out] actualLen   Returns the actual length of the response payload received from A-Core.
 * @param[out] cbResult    Buffer to store the result produced by the M-Core callback handler (pass NULL if not needed/registered).
 * @param[out] cbResultLen Returns the length of the callback result (pass NULL if not needed/registered).
 *
 * @return PICC_E_OK       = A-Core has responded and data is retrieved.
 *         PICC_E_NO_DATA  = A-Core has not responded yet.
 *         PICC_E_PARAM    = Invalid parameters provided.
 */
sint8 PICC_GetResponseData(PICC_AppIndex_e appIndex, uint8 methodId,
                           uint8 sessionId, uint8 *returnCode,
                           uint8 *data, uint16 maxLen, uint16 *actualLen,
                           uint8 *cbResult, uint16 *cbResultLen)
{
    return PICC_MailboxGetResponseData(appIndex, methodId, sessionId, returnCode,
                                       data, maxLen, actualLen,
                                       cbResult, cbResultLen);
}

/**
 * @brief Retrieve an Event Notification sent by A-Core to M-Core (Fire & Forget)
 *
 * Polling API for M-Core application tasks to check if A-Core has broadcast an Event.
 * If an 'eventHandler' was registered (e.g., to capture timestamps instantly), the 
 * result generated by that callback is simultaneously collected via 'cbResult'.
 *
 * @param[in]  appIndex    M-Core Application index (e.g., PICC_APP_TIMESYNC).
 * @param[in]  eventId     The specific Event ID M-Core is checking for.
 * @param[out] data        Buffer to store the payload data broadcasted by A-Core.
 * @param[in]  maxLen      Maximum size of the 'data' buffer provided by M-Core.
 * @param[out] actualLen   Returns the actual length of the event payload received from A-Core.
 * @param[out] cbResult    Buffer to store the result produced by the M-Core callback handler (pass NULL if not needed/registered).
 * @param[out] cbResultLen Returns the length of the callback result (pass NULL if not needed/registered).
 *
 * @return PICC_E_OK       = New event from A-Core was successfully retrieved.
 *         PICC_E_NO_DATA  = No new event from A-Core has arrived.
 *         PICC_E_PARAM    = Invalid parameters provided.
 */
sint8 PICC_GetEventData(PICC_AppIndex_e appIndex, uint8 eventId,
                        uint8 *data, uint16 maxLen, uint16 *actualLen,
                        uint8 *cbResult, uint16 *cbResultLen)
{
    return PICC_MailboxGetEventData(appIndex, eventId, data, maxLen, actualLen,
                                    cbResult, cbResultLen);
}

/*==================================================================================================
 *                              Public API — Status (1 function)
 *==================================================================================================*/

/**
 * @brief Get the physical channel health state (heartbeat-based)
 */
PICC_LinkState_e PICC_GetLinkState(uint8 channelId)
{
    return PICC_LinkGetState(channelId);
}

/**
 * @brief Get the application-level link connection state (per-app)
 *
 * Looks up the app's (localId, remoteId) from its registration config,
 * then queries the link layer for that specific pair's connection state.
 */
PICC_LinkState_e PICC_GetAppLinkState(PICC_AppIndex_e appIndex)
{
    const PICC_AppConfig_t *cfg;
    sint8 ret;

    ret = PICC_MailboxGetAppConfig(appIndex, &cfg);
    if (ret != PICC_E_OK) {
        return PICC_LINK_STATE_DISCONNECTED;
    }

    return PICC_LinkGetStateByIds(cfg->localId, cfg->remoteId);
}

#if defined(__cplusplus)
}
#endif
